// src/app/layout.js
import { LanguageProvider } from "../app/contaxt/LanguageContext";
import "./globals.css";

export const metadata = {
  title: "sxodim",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Оборачиваем все дочерние элементы в LanguageProvider для доступа к контексту */}
        <LanguageProvider>
          {children}
        </LanguageProvider>
      </body>
    </html>
  );
}
