// src/app/layout.js
import Header from "@/components/header/Header";
import { LanguageProvider } from "../context/LanguageContext";
import "./globals.css";
import Footer from "@/components/footer/Footer";

export const metadata = {
  title: "sxodim",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        {/* Оборачиваем все дочерние элементы в LanguageProvider для доступа к контексту */}
        <LanguageProvider>
          <Header/>
          {children}
          <Footer/>
        </LanguageProvider>
      </body>
    </html>
  );
}
